# HW 2

> Name: Maira Bermeo  
> EMPL ID: 24175075

#### Problem 1:

Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

In [4]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

a_clean= np.unique(a)
b_clean= np.unique(b)

unique = np.intersect1d(a_clean, b_clean)
print("Distinct/unique common items: " +str(unique)) 

Distinct/unique common items: [2 4]


#### Problem 2:

Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.

1   6    11  
2   7    12  
3   8    13  
4   9    14  
5   10  15  


In [7]:
array = np.arange(1, 16)
array_fixed = array.reshape(3, 5)
result = np.transpose(array_fixed)

print(result)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


#### Problem 3:

The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [15]:
flat = result.flatten()
flattened = np.sort(flat)
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


#### Problem 4:

Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [20]:
three_d = result.T.reshape(3, 5, 1)
print("3D Array shape:", three_d.shape)
print(three_d)

3D Array shape: (3, 5, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


#### Problem 5:

Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

In [11]:
back_to_2d = three_d.reshape(3, 5).transpose(1, 0)
print(back_to_2d)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


#### Problem 6:

You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [13]:
a = np.array([12, 5, 7, 15, 3, 1, 8]) 
b = np.array([14, 6, 3, 11, 19, 12, 5])

new = a[~np.isin(a, b)]
print("Filtered array:"+ str(new))

Filtered array:[ 7 15  1  8]


#### Problem 7:

Answer the following questions about the accompanying data file.  

What is the maximum yearly NYC consumption of water in millions of gallons per day?  
How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.  
What is the mean and the standard deviation of the per capita daily water consumption?  
What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an arrayof differences and save that to a variable called "pop_diff", then print that variable to the screen.  

In [15]:
import pandas as pd

NYC_consumption = pd.read_excel('Module6_Data.xlsx')

print(NYC_consumption.head())

   Year  New York City Population  NYC Consumption(Million gallons per day)  \
0  1979                 7102100.0                                    1512.0   
1  1980                 7071639.0                                    1506.0   
2  1981                 7089241.0                                    1309.0   
3  1982                 7109105.0                                    1382.0   
4  1983                 7181224.0                                    1424.0   

   Per Capita(Gallons per person per day)  
0                                     213  
1                                     213  
2                                     185  
3                                     194  
4                                     198  


In [16]:
# What is the maximum yearly NYC consumption of water in millions of gallons per day?  
max_consumption = NYC_consumption['NYC Consumption(Million gallons per day)'].max()
print("Max yearly NYC water consumption (MGD): "+ str(max_consumption))


Max yearly NYC water consumption (MGD): 1512.0


In [17]:
# How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
num_years = NYC_consumption.shape[0]
print("Number of calendar years represented: " + str(num_years))

Number of calendar years represented: 39


In [18]:
# What is the mean and the standard deviation of the per capita daily water consumption?  
mean_per_capita = NYC_consumption['Per Capita(Gallons per person per day)'].mean()
std_per_capita = NYC_consumption['Per Capita(Gallons per person per day)'].std()

print("Mean per capita (GPCD): "+ str(mean_per_capita))
print("Standard deviation of per capita (GPCD): "+ str( std_per_capita))

Mean per capita (GPCD): 160.30769230769232
Standard deviation of per capita (GPCD): 31.930973122258784


In [19]:
# What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an arrayof 
# differences and save that to a variable called "pop_diff", then print that variable to the screen.  
pop_diff = np.diff(NYC_consumption['New York City Population'])
print("Year-over-year population change: "+ str( pop_diff))

Year-over-year population change: [-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
